### PR TITLE
Add missing integrity check

### PR DESCRIPTION
**Pull request by TheAssassin**

### CODE REVIEW

**Comment by TheAssassin** [comment]
@probonopd could you merge this some day please?

**Comment by probonopd** [comment]
Sorry it took so long. There seems to be a merge conflict now, can you please have a look at resolving it? Thank you very much.

**Comment by TheAssassin** [comment]
Well, you removed the code which is attempted to be patched here. So, you tell me. The file isn't used any more as it seems, so all I could do to resolve the conflict is add it as a comment, which is a bit pointless.

But, you could take the idea of this PR and apply it elsewhere. It is a *really* bad idea to pull in external files without verifying it's actually them. I've seen these cases in many, many projects, and fixed them where applicable.

**Comment by probonopd** [comment]
Ah, OK, i see. So closing here.

Question: Isn't adding a checksum a sort of endorsement? Wouldn't it mean that we would be sure that what we checksum is "known good" (has not been compromised)? And how would we go about actually verifying this?

**Comment by TheAssassin** [comment]
Well, the idea is, that one day you implement code using that file, you hash it to make sure it won't be changed in the future without further notice. This prevents a lot of attacks. Even if you can't verify it initially, at least the attack vector of changing it e.g., during a MITM attack, is closed.

**Pull request closed without merging**
